version: '3.7'

services:

  app:
    build: 
      context: ./app
      dockerfile: docker/Dockerfile
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - ./output:/app/output
    command: streamlit run app.py
    ports:
      - 8501:8501
  
  
  api:
    build:
      context: ./api
      dockerfile: docker/Dockerfile
    platform: linux/amd64
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 80
    ports:
      - 80:80
    env_file:
      - .env

  web:
    build:
      context: ./scraping
      dockerfile: docker/Dockerfile
    platform: linux/amd64
    restart: unless-stopped
    depends_on: [api]
    environment:
    - PYTHONUNBUFFERED=1
    volumes:
      - ./output:/scraping/output
    ports:
      - 8080:8080

volumes:
  output: