version: '3.7'

services:

  app:
    build: 
      context: ./app
      dockerfile: docker/Dockerfile
    platform: linux/amd64
    restart: unless-stopped
    command: streamlit run app.py
    ports:
      - 8501:8501
  
  
  api:
    build:
      context: ./api
      dockerfile: docker/Dockerfile
    platform: linux/amd64
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env