# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build Containers for CNU Data Dashboard - cnuStatsApp Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.AzureAppService_ContainerUsername_264c9a4b8acd41ef96e3fbe0b252a0bc }}
          password: ${{ secrets.AzureAppService_ContainerPassword_e7819aeed4ed40f7a3938fbdbae9df93 }}

      - name: Build and push App container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./app
          tags: nater55/cnumbbmlproject-app:prod
          file: ./app/Dockerfile

      - name: Build and push container Web image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./scraping
          tags: nater55/cnumbbmlproject-web:prod
          file: ./scraping/Dockerfile
